# unite plugins
[[plugins]]
repo    = 'Shougo/unite.vim'

[[plugins]]
repo    = 'ujihisa/unite-colorscheme'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'ujihisa/unite-locate'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'tacroe/unite-mark'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'zhaocai/unite-scriptnames'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'thinca/vim-editvar'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'thinca/vim-unite-history'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'ujihisa/unite-launch'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'Shougo/neomru.vim'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'tsukkee/unite-tag'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'sorah/unite-ghq'
depends = ['Shougo/unite.vim']
# unite plugins
