# utils plugins
[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'

[[plugins]]
repo = 'akiyan/vim-textobj-xml-attribute'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1
  noremap <silent><C-f> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'vim-scripts/SQLUtilities'

#[[plugins]]
#repo = 'sgur/vim-gf-autoload'

[[plugins]]
repo = 't9md/vim-choosewin'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
noremap U :GundoToggle<CR>
'''
# utils plugins
