# language plugins
[[plugins]]
repo = 'thinca/vim-prettyprint'
on_ft = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml','yml']

[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['yaml','yml']
hook_add = '''
 let g:ansible_unindent_after_newline = 1
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = 'javascript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# language plugins
