# syntax plugins

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
let g:syntastic_python_checkers = ['pyflakes', 'pep8']
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_emit_conflict_warnings = 0
let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
" ファイルオープン時にチェックしたくない場合
let g:ale_lint_on_enter = 0
let g:ale_open_list = 1
" エラーと警告がなくなっても開いたままにする
let g:ale_keep_list_window_open = 1
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim', 'kana/vim-textobj-user']

[[plugins]]
repo = 'elzr/vim-json'

# syntax plugins
